// Generated by make_body_colours.py: do not edit.
namespace RealStars;

internal static partial class BodyColours
{
    /// <summary>Measured colours of the Sun's bodies by template Id: each one's albedo per channel with the Sun
    /// as white, linear sRGB at unit luminance. make_body_colours.py has the measurements behind each.</summary>
    internal static readonly Dictionary<string, float[]> Measured = new()
    {
        ["Mercury"] = new[] { 1.1319f, 0.9839f, 0.7707f },   // Mallama et al. 2017, Table 7
        ["Venus"] = new[] { 1.0032f, 1.0097f, 0.8941f },   // Mallama et al. 2017, Table 7
        ["Earth"] = new[] { 0.8911f, 1.0091f, 1.2307f },   // Mallama et al. 2017, Table 7
        ["Luna"] = new[] { 1.1421f, 0.9765f, 0.8145f },   // Lane & Irvine 1973; McCord & Johnson 1970
        ["Mars"] = new[] { 1.3902f, 0.9342f, 0.5017f },   // Mallama et al. 2017, Table 7
        ["Jupiter"] = new[] { 1.0152f, 1.0113f, 0.8437f },   // Karkoschka 1998
        ["Io"] = new[] { 1.0751f, 1.0076f, 0.7035f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Europa"] = new[] { 1.0031f, 1.0105f, 0.8867f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Ganymede"] = new[] { 1.0158f, 1.0037f, 0.9171f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Callisto"] = new[] { 1.0245f, 1.0045f, 0.8834f },   // Mayorga et al. 2020, on Ganymede's spectrum
        ["Amalthea"] = new[] { 1.3247f, 0.9505f, 0.5343f },   // Kulyk & Jockers 2004, B-V; red through the visible (Thomas et al. 1998)
        ["Himalia"] = new[] { 1.0149f, 0.9962f, 0.9940f },   // Neese 2004 (PDS), mean
        ["Elara"] = new[] { 1.0072f, 0.9996f, 0.9830f },   // Neese 2004 (PDS), mean
        ["Pasiphae"] = new[] { 1.0402f, 0.9933f, 0.9479f },   // Neese 2004 (PDS), mean
        ["Sinope"] = new[] { 1.0983f, 0.9832f, 0.8766f },   // Neese 2004 (PDS), mean
        ["Lysithea"] = new[] { 1.0218f, 0.9968f, 0.9675f },   // Neese 2004 (PDS), mean
        ["Saturn"] = new[] { 1.1392f, 0.9915f, 0.6745f },   // Karkoschka 1998, rings edge-on
        ["Mimas"] = new[] { 1.0015f, 1.0003f, 0.9923f },   // Franz 1975 (B-V only)
        ["Enceladus"] = new[] { 0.9970f, 0.9993f, 1.0156f },   // Cruikshank 1980 (B-V only)
        ["Tethys"] = new[] { 1.0143f, 1.0035f, 0.9234f },   // Cruikshank 1980
        ["Dione"] = new[] { 1.0172f, 1.0039f, 0.9109f },   // Cruikshank 1980
        ["Rhea"] = new[] { 1.0170f, 1.0041f, 0.9092f },   // Cruikshank 1980
        ["Titan"] = new[] { 1.2801f, 0.9646f, 0.5258f },   // Karkoschka 1998
        ["Iapetus"] = new[] { 1.0117f, 1.0026f, 0.9400f },   // Stephan 2009 (B-V only)
        ["Uranus"] = new[] { 0.6889f, 1.0756f, 1.1676f },   // Karkoschka 1998
        ["Titania"] = new[] { 1.0086f, 1.0022f, 0.9529f },   // Cruikshank 1980
        ["Oberon"] = new[] { 1.0059f, 1.0013f, 0.9695f },   // Cruikshank 1980
        ["Neptune"] = new[] { 0.6050f, 1.0820f, 1.3511f },   // Karkoschka 1998
        ["Triton"] = new[] { 1.0117f, 1.0026f, 0.9400f },   // Degewij et al. 1980 (B-V only)
        ["Pluto"] = new[] { 1.1484f, 0.9812f, 0.7488f },   // Buie et al. 2010; Verbiscer et al. 2022
        ["Charon"] = new[] { 1.0435f, 0.9951f, 0.9202f },   // Buie et al. 2010; Verbiscer et al. 2022
        ["Eris"] = new[] { 1.0469f, 0.9990f, 0.8715f },   // Hainaut et al. 2012 (MBOSS)
        ["Haumea"] = new[] { 1.0106f, 0.9966f, 1.0021f },   // Hainaut et al. 2012 (MBOSS)
        ["MakemakeComet"] = new[] { 1.0628f, 0.9963f, 0.8515f },   // Hainaut et al. 2012; Hromakina et al. 2019 (Makemake)
        ["Sedna"] = new[] { 1.2602f, 0.9596f, 0.6337f },   // Hainaut et al. 2012 (MBOSS)
        ["Ceres"] = new[] { 1.0076f, 1.0019f, 0.9592f },   // Zellner et al. 1985 (ECAS)
        ["Pallas"] = new[] { 0.9950f, 1.0016f, 0.9994f },   // Zellner et al. 1985 (ECAS)
        ["Vesta"] = new[] { 1.0554f, 0.9956f, 0.8807f },   // Zellner et al. 1985 (ECAS)
        ["Hygiea"] = new[] { 0.9932f, 1.0031f, 0.9892f },   // Zellner et al. 1985 (ECAS)
        ["Eros"] = new[] { 1.1301f, 0.9827f, 0.7883f },   // Zellner et al. 1985 (ECAS)
        ["HalleysComet"] = new[] { 1.0469f, 0.9930f, 0.9316f },   // Hainaut et al. 2012, nucleus (V-R only)
        ["HaleBoppComet"] = new[] { 1.0938f, 0.9852f, 0.8701f },   // Jewitt 2015, long-period comet mean
        ["LovejoyComet"] = new[] { 1.0938f, 0.9852f, 0.8701f },   // Jewitt 2015, long-period comet mean
        ["Oumuamua"] = new[] { 1.0698f, 0.9862f, 0.9310f },   // Jewitt et al. 2017
        ["Borisov"] = new[] { 1.0965f, 0.9858f, 0.8566f },   // Jewitt & Luu 2019, dust
        ["3I_ATLAS"] = new[] { 1.1448f, 0.9779f, 0.7923f },   // Opitom et al. 2025, dust, 18 %/100 nm
    };
}
