// Generated by make_body_colours.py: do not edit.
namespace RealStars;

internal static partial class BodyColours
{
    /// <summary>Measured colours of the Sun's bodies by template Id: each one's albedo per channel with the Sun
    /// as white, linear sRGB at unit luminance. make_body_colours.py has the measurements behind each.</summary>
    internal static readonly Dictionary<string, float[]> Measured = new()
    {
        ["Mercury"] = new[] { 1.1299f, 0.9848f, 0.7680f },   // Mallama et al. 2017, Table 7
        ["Venus"] = new[] { 1.0029f, 1.0102f, 0.8910f },   // Mallama et al. 2017, Table 7
        ["Earth"] = new[] { 0.8929f, 1.0082f, 1.2345f },   // Mallama et al. 2017, Table 7
        ["Luna"] = new[] { 1.1405f, 0.9772f, 0.8122f },   // Lane & Irvine 1973; McCord & Johnson 1970
        ["Mars"] = new[] { 1.3853f, 0.9361f, 0.4975f },   // Mallama et al. 2017, Table 7
        ["Jupiter"] = new[] { 1.0143f, 1.0118f, 0.8409f },   // Karkoschka 1998
        ["Io"] = new[] { 1.0737f, 1.0086f, 0.6975f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Europa"] = new[] { 1.0027f, 1.0109f, 0.8845f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Ganymede"] = new[] { 1.0153f, 1.0040f, 0.9153f },   // Johnson & McCord 1971; Mayorga et al. 2020
        ["Callisto"] = new[] { 1.0238f, 1.0049f, 0.8812f },   // Mayorga et al. 2020, on Ganymede's spectrum
        ["Amalthea"] = new[] { 1.3206f, 0.9522f, 0.5290f },   // Kulyk & Jockers 2004, B-V; red through the visible (Thomas et al. 1998)
        ["Himalia"] = new[] { 1.0148f, 0.9962f, 0.9940f },   // Neese 2004 (PDS), mean
        ["Elara"] = new[] { 1.0070f, 0.9996f, 0.9828f },   // Neese 2004 (PDS), mean
        ["Pasiphae"] = new[] { 1.0397f, 0.9935f, 0.9474f },   // Neese 2004 (PDS), mean
        ["Sinope"] = new[] { 1.0971f, 0.9837f, 0.8754f },   // Neese 2004 (PDS), mean
        ["Lysithea"] = new[] { 1.0215f, 0.9969f, 0.9671f },   // Neese 2004 (PDS), mean
        ["Saturn"] = new[] { 1.1369f, 0.9927f, 0.6689f },   // Karkoschka 1998, rings edge-on
        ["Mimas"] = new[] { 1.0014f, 1.0004f, 0.9922f },   // Franz 1975 (B-V only)
        ["Enceladus"] = new[] { 0.9971f, 0.9993f, 1.0158f },   // Cruikshank 1980 (B-V only)
        ["Tethys"] = new[] { 1.0138f, 1.0038f, 0.9222f },   // Cruikshank 1980
        ["Dione"] = new[] { 1.0166f, 1.0042f, 0.9096f },   // Cruikshank 1980
        ["Rhea"] = new[] { 1.0164f, 1.0044f, 0.9077f },   // Cruikshank 1980
        ["Titan"] = new[] { 1.2759f, 0.9663f, 0.5211f },   // Karkoschka 1998
        ["Iapetus"] = new[] { 1.0113f, 1.0028f, 0.9392f },   // Stephan 2009 (B-V only)
        ["Uranus"] = new[] { 0.6932f, 1.0743f, 1.1679f },   // Karkoschka 1998
        ["Titania"] = new[] { 1.0083f, 1.0024f, 0.9521f },   // Cruikshank 1980
        ["Oberon"] = new[] { 1.0057f, 1.0014f, 0.9691f },   // Cruikshank 1980
        ["Neptune"] = new[] { 0.6110f, 1.0800f, 1.3539f },   // Karkoschka 1998
        ["Triton"] = new[] { 1.0113f, 1.0028f, 0.9392f },   // Degewij et al. 1980 (B-V only)
        ["Pluto"] = new[] { 1.1462f, 0.9822f, 0.7458f },   // Buie et al. 2010; Verbiscer et al. 2022
        ["Charon"] = new[] { 1.0428f, 0.9954f, 0.9193f },   // Buie et al. 2010; Verbiscer et al. 2022
        ["Eris"] = new[] { 1.0459f, 0.9995f, 0.8699f },   // Hainaut et al. 2012 (MBOSS)
        ["Haumea"] = new[] { 1.0105f, 0.9966f, 1.0022f },   // Hainaut et al. 2012 (MBOSS)
        ["MakemakeComet"] = new[] { 1.0617f, 0.9968f, 0.8496f },   // Hainaut et al. 2012; Hromakina et al. 2019 (Makemake)
        ["Sedna"] = new[] { 1.2568f, 0.9610f, 0.6297f },   // Hainaut et al. 2012 (MBOSS)
        ["Ceres"] = new[] { 1.0073f, 1.0020f, 0.9582f },   // Zellner et al. 1985 (ECAS)
        ["Pallas"] = new[] { 0.9950f, 1.0016f, 0.9991f },   // Zellner et al. 1985 (ECAS)
        ["Vesta"] = new[] { 1.0545f, 0.9960f, 0.8789f },   // Zellner et al. 1985 (ECAS)
        ["Hygiea"] = new[] { 0.9932f, 1.0032f, 0.9886f },   // Zellner et al. 1985 (ECAS)
        ["Eros"] = new[] { 1.1282f, 0.9835f, 0.7857f },   // Zellner et al. 1985 (ECAS)
        ["HalleysComet"] = new[] { 1.0462f, 0.9932f, 0.9309f },   // Hainaut et al. 2012, nucleus (V-R only)
        ["HaleBoppComet"] = new[] { 1.0925f, 0.9857f, 0.8687f },   // Jewitt 2015, long-period comet mean
        ["LovejoyComet"] = new[] { 1.0925f, 0.9857f, 0.8687f },   // Jewitt 2015, long-period comet mean
        ["Oumuamua"] = new[] { 1.0691f, 0.9865f, 0.9304f },   // Jewitt et al. 2017
        ["Borisov"] = new[] { 1.0952f, 0.9863f, 0.8550f },   // Jewitt & Luu 2019, dust
        ["3I_ATLAS"] = new[] { 1.1430f, 0.9787f, 0.7900f },   // Opitom et al. 2025, dust, 18 %/100 nm
    };
}
