# -*- coding: utf-8 -*-
"""What a star the catalogue does not have would look like, from what the game knows about it.

The game's own stars are drawn with the catalogue's measurements wherever the catalogue has them
(GameStars.cs). A star it does not have, a modded system's own star, is known only by the mass,
radius and light its template gives, so its brightness is worked out from those:

  On the main sequence, a dwarf's brightness follows from its mass. When the radius is what a dwarf
  of that mass has (within a factor of two), the V absolute magnitude is the measured mean dwarf
  sequence's at that mass: Pecaut & Mamajek (2013, ApJS 208, 9), Table 5, as Mamajek keeps it
  updated (version 2022.04.16). From Proxima Centauri's mass and radius this gives M_V 15.3,
  measured 15.45; from Alpha Centauri A's, 4.35 against 4.34.

  Anything else (a giant, a white dwarf) is worked out from its size and temperature: the
  temperature from the colour of its light, which is raw by Real Stars' convention (the blackbody
  colour make_star_binary.py gives every star), the luminosity from Stefan-Boltzmann, and V through
  the same sequence's bolometric corrections by temperature.

The colour of the light is NOT used where the mass will do: the stock stars' lights are paler than
their temperatures (Proxima's reads as 3,985 K, against 3,042 K), and through the colour Proxima
would come out four magnitudes too bright.

Writes StarEstimates.Generated.cs. The table is downloaded to assets/ on first run.
"""
import os
import urllib.request
import numpy as np

from make_star_binary import blackbody_srgb

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "StarEstimates.Generated.cs")
TABLE = "https://www.pas.rochester.edu/~emamajek/EEM_dwarf_UBVIJHK_colors_Teff.txt"
TABLE_PATH = os.path.join(HERE, "assets", "EEM_dwarf_UBVIJHK_colors_Teff.txt")


def dwarf_sequence():
    """(mass, M_V, radius, Teff, BC_V) for every dwarf the table gives all five for."""
    if not os.path.exists(TABLE_PATH):
        os.makedirs(os.path.dirname(TABLE_PATH), exist_ok=True)
        print(f"  downloading {TABLE}")
        with urllib.request.urlopen(TABLE, timeout=120) as r, open(TABLE_PATH, "wb") as f:
            f.write(r.read())
    with open(TABLE_PATH, encoding="latin-1") as f:
        lines = f.read().splitlines()
    header = next(i for i, l in enumerate(lines) if l.startswith("#SpT"))
    names = lines[header].lstrip("#").split()
    col = {n: names.index(n) for n in ("SpT", "Teff", "BCv", "R_Rsun", "Mv", "Msun")}
    rows = []
    for l in lines[header + 1:]:
        if l.startswith("#"):
            break                                  # the table's second header closes it
        p = l.split()
        try:
            rows.append((float(p[col["Msun"]]), float(p[col["Mv"]]), float(p[col["R_Rsun"]]),
                         float(p[col["Teff"]]), float(p[col["BCv"]]), p[col["SpT"]]))
        except (ValueError, IndexError):
            continue                               # "..." in a column we need
    return rows


def locus():
    """Blackbody colours, peak-normalised linear sRGB, every 2% in temperature from 1,000 to 40,000 K."""
    T = np.exp(np.arange(np.log(1000.0), np.log(40000.0) + 1e-9, np.log(1.02)))
    rgb = blackbody_srgb(T)
    return T, rgb / np.maximum(rgb.max(1, keepdims=True), 1e-12)


def floats(values, per_line=8, fmt="{:.6g}f"):
    out, line = [], []
    for v in values:
        line.append(fmt.format(v))
        if len(line) == per_line:
            out.append("        " + ", ".join(line) + ",")
            line = []
    if line:
        out.append("        " + ", ".join(line) + ",")
    return out


def main():
    rows = dwarf_sequence()
    by_mass = sorted(rows, key=lambda r: r[0])
    by_teff = sorted(rows, key=lambda r: r[3])
    T, rgb = locus()
    print(f"{len(rows)} dwarfs, {by_mass[0][5]} ({by_mass[0][0]} Msun) to {by_mass[-1][5]} ({by_mass[-1][0]} Msun); "
          f"locus {len(T)} temperatures, {T[0]:.0f} to {T[-1]:.0f} K")

    lines = ["// Generated by make_star_estimates.py: do not edit.",
             "namespace RealStars;",
             "",
             "internal static partial class GameStars",
             "{",
             "    /// <summary>The mean dwarf sequence (Pecaut & Mamajek 2013, Table 5; Mamajek's version 2022.04.16) by mass:",
             "    /// solar masses, V absolute magnitude, solar radii.</summary>"]
    lines += ["    private static readonly float[] DwarfMass =", "    {"] + floats([r[0] for r in by_mass]) + ["    };"]
    lines += ["    private static readonly float[] DwarfMv =", "    {"] + floats([r[1] for r in by_mass]) + ["    };"]
    lines += ["    private static readonly float[] DwarfRadius =", "    {"] + floats([r[2] for r in by_mass]) + ["    };", ""]
    lines += ["    /// <summary>The same sequence by temperature: kelvin, and the bolometric correction to V.</summary>",
              "    private static readonly float[] DwarfTeff =", "    {"] + floats([r[3] for r in by_teff]) + ["    };"]
    lines += ["    private static readonly float[] DwarfBCv =", "    {"] + floats([r[4] for r in by_teff]) + ["    };", ""]
    lines += ["    /// <summary>Blackbody colours as make_star_binary.py gives every star: linear sRGB against D65, brightest",
              "    /// channel 1, every 2% in temperature.</summary>",
              "    private static readonly float[] LocusKelvin =", "    {"] + floats(T, fmt="{:.1f}f") + ["    };"]
    for name, k in (("LocusRed", 0), ("LocusGreen", 1), ("LocusBlue", 2)):
        lines += [f"    private static readonly float[] {name} =", "    {"] + floats(rgb[:, k], fmt="{:.5f}f") + ["    };"]
    lines += ["}", ""]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {OUT}")

    # What the stock stars' own data say, against their measured V (AT-HYG, as the catalogue has it).
    stock = (("Sol", 1.0, 696342, 4.80), ("AlphaCentauriA", 1.0788, 851928, 4.38), ("AlphaCentauriB", 0.9092, 601309, 5.74),
             ("ProximaCentauri", 0.1221, 107412, 15.44), ("BarnardsStar", 0.162, 130096, 13.23), ("TauCeti", 0.8, 551690, 5.68))
    m, mv, rr = (np.array([r[i] for r in by_mass]) for i in range(3))
    for name, mass, km, measured in stock:
        r_ms = np.exp(np.interp(np.log(mass), np.log(m), np.log(rr)))
        est = np.interp(np.log(mass), np.log(m), mv)
        print(f"  {name:16s} M {mass:6.4f}: radius {km / 695700:.3f} vs a dwarf's {r_ms:.3f} -> M_V {est:5.2f} (measured {measured:5.2f})")


if __name__ == "__main__":
    main()
