// Generated by make_star_binary.py: do not edit.
namespace RealStars;

internal static partial class SunLight
{
    /// <summary>The Sun's raw colour: a measured solar spectrum (CALSPEC sun_reference_stis_002) against the
    /// display's D65 white, brightest channel 1, as star_colours.py gives every star. The catalogue stores it
    /// as (255, 231, 219).</summary>
    internal static readonly float[] SunRaw = { 1.00000f, 0.90587f, 0.85898f };

    /// <summary>The stock interstellar stars by Id: the light the game gives each, and the raw colour of the
    /// star in the catalogue (its measured B-V on the dwarf sequence of real spectra).</summary>
    private static readonly Dictionary<string, (float R, float G, float B, float[] Raw, string Source)> StockStars = new()
    {
        ["AlphaCentauriA"] = (9.2f, 9.1f, 8.7f, new[] { 1.00000f, 0.88830f, 0.79847f }, "HIP 71683, B-V 0.710"),
        ["AlphaCentauriB"] = (9.2f, 8.4f, 7.0f, new[] { 1.00000f, 0.76245f, 0.59191f }, "HIP 71681, B-V 0.900"),
        ["ProximaCentauri"] = (9.0f, 5.8f, 3.4f, new[] { 1.00000f, 0.61110f, 0.20897f }, "HIP 70890, B-V 1.807"),
        ["BarnardsStar"] = (9.0f, 6.4f, 3.8f, new[] { 1.00000f, 0.62232f, 0.24594f }, "HIP 87937, B-V 1.570"),
        ["TauCeti"] = (9.0f, 8.3f, 7.6f, new[] { 1.00000f, 0.87231f, 0.77233f }, "HIP 8102, B-V 0.727"),
    };
}
